#ifndef TYPE_H
#define TYPE_H

#include <stdint.h>

typedef enum Side : uint8_t {
    SIDE_WHITE,
    SIDE_BLACK,
} Side;

typedef enum PieceType : uint8_t {
    PIECE_TYPE_ROOK,
    PIECE_TYPE_KNIGHT,
    PIECE_TYPE_BISHOP,
    PIECE_TYPE_QUEEN,
    PIECE_TYPE_KING,
    PIECE_TYPE_PAWN
} PieceType;

typedef enum PieceId : uint8_t {
    PIECE_ID_BLACK_ROOK_QUEEN_SIDE,
    PIECE_ID_BLACK_KNIGHT_QUEEN_SIDE,
    PIECE_ID_BLACK_BISHOP_QUEEN_SIDE,
    PIECE_ID_BLACK_QUEEN,
    PIECE_ID_BLACK_KING,
    PIECE_ID_BLACK_BISHOP_KING_SIDE,
    PIECE_ID_BLACK_KNIGHT_KING_SIDE,
    PIECE_ID_BLACK_ROOK_KING_SIDE,
    PIECE_ID_BLACK_PAWN_1,
    PIECE_ID_BLACK_PAWN_2,
    PIECE_ID_BLACK_PAWN_3,
    PIECE_ID_BLACK_PAWN_4,
    PIECE_ID_BLACK_PAWN_5,
    PIECE_ID_BLACK_PAWN_6,
    PIECE_ID_BLACK_PAWN_7,
    PIECE_ID_BLACK_PAWN_8,
    PIECE_ID_WHITE_ROOK_QUEEN_SIDE,
    PIECE_ID_WHITE_KNIGHT_QUEEN_SIDE,
    PIECE_ID_WHITE_BISHOP_QUEEN_SIDE,
    PIECE_ID_WHITE_QUEEN,
    PIECE_ID_WHITE_KING,
    PIECE_ID_WHITE_BISHOP_KING_SIDE,
    PIECE_ID_WHITE_KNIGHT_KING_SIDE,
    PIECE_ID_WHITE_ROOK_KING_SIDE,
    PIECE_ID_WHITE_PAWN_1,
    PIECE_ID_WHITE_PAWN_2,
    PIECE_ID_WHITE_PAWN_3,
    PIECE_ID_WHITE_PAWN_4,
    PIECE_ID_WHITE_PAWN_5,
    PIECE_ID_WHITE_PAWN_6,
    PIECE_ID_WHITE_PAWN_7,
    PIECE_ID_WHITE_PAWN_8,
} PieceId;

typedef enum MoveFlags : uint8_t {
    MOVE_FLAGS_HAS_MOVING_PIECE = 1 << 0,
    MOVE_FLAGS_HAS_TAKING_PIECE = 1 << 1,
    MOVE_FLAGS_HAS_PROMOTION = 1 << 2,
    MOVE_FLAGS_HAS_CASTLING = 1 << 3,
} MoveFlags;

typedef enum MoveCastlingType : uint8_t {
    MOVE_CASTLING_TYPE_KING_SIDE,
    MOVE_CASTLING_TYPE_QUEEN_SIDE
} MoveCastlingType;

#endif