#ifndef ENUMS_H
#define ENUMS_H

#include <stdint.h>

typedef enum side_t : uint8_t {
  SIDE_WHITE,
  SIDE_BLACK,
} side_t;

typedef enum piece_type_t : uint8_t {
  PIECE_TYPE_ROOK,
  PIECE_TYPE_KNIGHT,
  PIECE_TYPE_BISHOP,
  PIECE_TYPE_QUEEN,
  PIECE_TYPE_KING,
  PIECE_TYPE_PAWN
} piece_type_t;

typedef enum piece_id_t : uint8_t {
  PIECE_ID_BLACK_ROOK_1,
  PIECE_ID_BLACK_KNIGHT_1,
  PIECE_ID_BLACK_BISHOP_1,
  PIECE_ID_BLACK_QUEEN,
  PIECE_ID_BLACK_KING,
  PIECE_ID_BLACK_BISHOP_2,
  PIECE_ID_BLACK_KNIGHT_2,
  PIECE_ID_BLACK_ROOK_2,
  PIECE_ID_BLACK_PAWN_1,
  PIECE_ID_BLACK_PAWN_2,
  PIECE_ID_BLACK_PAWN_3,
  PIECE_ID_BLACK_PAWN_4,
  PIECE_ID_BLACK_PAWN_5,
  PIECE_ID_BLACK_PAWN_6,
  PIECE_ID_BLACK_PAWN_7,
  PIECE_ID_BLACK_PAWN_8,
  PIECE_ID_WHITE_ROOK_1,
  PIECE_ID_WHITE_KNIGHT_1,
  PIECE_ID_WHITE_BISHOP_1,
  PIECE_ID_WHITE_QUEEN,
  PIECE_ID_WHITE_KING,
  PIECE_ID_WHITE_BISHOP_2,
  PIECE_ID_WHITE_KNIGHT_2,
  PIECE_ID_WHITE_ROOK_2,
  PIECE_ID_WHITE_PAWN_1,
  PIECE_ID_WHITE_PAWN_2,
  PIECE_ID_WHITE_PAWN_3,
  PIECE_ID_WHITE_PAWN_4,
  PIECE_ID_WHITE_PAWN_5,
  PIECE_ID_WHITE_PAWN_6,
  PIECE_ID_WHITE_PAWN_7,
  PIECE_ID_WHITE_PAWN_8,
  TOTAL_PIECES
} piece_id_t;

typedef enum move_flags_t : uint8_t {
  MOVE_FLAGS_HAS_MOVING_PIECE = 1 << 0,
  MOVE_FLAGS_HAS_TAKING_PIECE = 1 << 1,
  MOVE_FLAGS_HAS_PROMOTION = 1 << 2,
  MOVE_FLAGS_HAS_CASTLING = 1 << 3,
} move_flags_t;

typedef enum move_castling_type_t : uint8_t {
  MOVE_CASTLING_TYPE_KING_SIDE,
  MOVE_CASTLING_TYPE_QUEEN_SIDE
} move_castling_type_t;

#endif