#ifndef CHESS_ERROR_NO_H
#define CHESS_ERROR_NO_H

#define CHESS_OK 0
#define CHESS_ERROR -1
#define CHESS_ERROR_INVALID_ARGS -2
#define CHESS_ERROR_NO_MEMORY -3
#define CHESS_ERROR_CAST_PIECE_TYPE_MISMATCH -4
#define CHESS_ERROR_INVALID_STATE -5

#endif