#ifndef CHESS_DEF_H
#define CHESS_DEF_H

#define MAX_NUM_PIECES 64

#define PIECE_TYPE_ROOK 1
#define PIECE_TYPE_KNIGHT 2
#define PIECE_TYPE_BISHOP 3
#define PIECE_TYPE_QUEEN 4
#define PIECE_TYPE_KING 5
#define PIECE_TYPE_PAWN 6

#define ROOK_TYPE_KING_SIDE 1
#define ROOK_TYPE_QUEEN_SIDE 2

#define EMPTY 0

#define SIDE_WHITE 1
#define SIDE_BLACK 2

#define BOARD_HEIGHT 8
#define BOARD_WIDTH 8

#define MOVE_FLAGS_MOVE_PIECE (1 << 0)
#define MOVE_FLAGS_TAKE_PIECE (1 << 1)
#define MOVE_FLAGS_PROMOTE (1 << 2)
#define MOVE_FLAGS_CASTLE (1 << 3)

#define MOVE_CASTLE_KING 1
#define MOVE_CASTLE_QUEEN 2

#define MOVE_ARRAY_MAX_LENGTH 255
#define PIECE_MOVE_ID_ARRAY_MAX_LENGTH 32

#define NOTATION_DATA_MAX_SIZE 8
#define NOTATION_TYPE_POSITION 1
#define NOTATION_TYPE_MOVE 2

#endif
